import DashboardIcon from "@mui/icons-material/Dashboard";
import ReceiptIcon from "@mui/icons-material/Receipt";
import RequestQuote from "@mui/icons-material/RequestQuote";
import CreditScore from "@mui/icons-material/CreditScore";
import LogoutIcon from "@mui/icons-material/Logout";
import AddIcon from "@mui/icons-material/Add";
import BookIcon from "@mui/icons-material/Book";
import CurrencyBitcoinIcon from "@mui/icons-material/CurrencyBitcoin";
import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import SpaceDashboardIcon from "@mui/icons-material/SpaceDashboard";
import AdjustIcon from "@mui/icons-material/Adjust";
import CheckroomIcon from "@mui/icons-material/Checkroom";
import MarkUnreadChatAltIcon from "@mui/icons-material/MarkUnreadChatAlt";
import AttachMoneyIcon from "@mui/icons-material/AttachMoney";
import LocalDiningIcon from "@mui/icons-material/LocalDining";
import PhonelinkIcon from "@mui/icons-material/Phonelink";
import MedicalInformationIcon from "@mui/icons-material/MedicalInformation";
import MoneyIcon from "@mui/icons-material/Money";
import SavingsIcon from "@mui/icons-material/Savings";
import ShowChartIcon from "@mui/icons-material/ShowChart";
import CardGiftcardIcon from "@mui/icons-material/CardGiftcard";
import DeleteForeverIcon from "@mui/icons-material/DeleteForever";
import LiveTvIcon from "@mui/icons-material/LiveTv";
import GroupIcon from "@mui/icons-material/Group";
import YouTubeIcon from "@mui/icons-material/YouTube";

export const dashboard = <DashboardIcon />;
export const transactions = <ReceiptIcon />;
export const categories = <i className="fa-solid fa-tags"></i>;
export const accounts = <i className="fa-solid fa-wallet"></i>;
export const settings = <i className="fa-solid fa-cog"></i>;
export const logout = <LogoutIcon />;
export const trend = <CreditScore />;
export const expenses = <RequestQuote />;
export const money = <MoneyIcon />;
export const freelance = <PhonelinkIcon />;
export const stocks = <ShowChartIcon />;
export const bitcoin = <CurrencyBitcoinIcon />;
export const piggy = <SavingsIcon />;
export const yt = <YouTubeIcon />;
export const card = <SpaceDashboardIcon />;
export const users = <GroupIcon />;
export const dollar = <AttachMoneyIcon />;
export const calender = <CalendarMonthIcon />;
export const comment = <MarkUnreadChatAltIcon />;
export const plus = <AddIcon />;
export const trash = <DeleteForeverIcon />;
export const signout = <LogoutIcon />;
export const takeaway = <CardGiftcardIcon />;
export const clothing = <CheckroomIcon />;
export const book = <BookIcon />;
export const food = <LocalDiningIcon />;
export const medical = <MedicalInformationIcon />;
export const tv = <LiveTvIcon />;
export const circle = <AdjustIcon />;
